/*
  # Update Quiz Questions for Comprehensive Visa Coverage

  1. New Quiz Structure
    - Question 1: Primary purpose of visit/stay
    - Question 2: Employment/study/personal situation
    - Question 3: Duration and intent
    - Question 4: Special circumstances

  2. Coverage
    - All nonimmigrant visa categories
    - Immigrant visa options
    - Visa Waiver Program
*/

-- Insert comprehensive quiz questions
INSERT INTO quiz_questions (question_translations, question_order, question_type)
VALUES
  ('{"en": "What is the primary purpose of your visit or stay in the United States?", "es": "¿Cuál es el propósito principal de su visita o estancia en Estados Unidos?", "zh": "您在美国访问或停留的主要目的是什么？", "fr": "Quel est le but principal de votre visite ou séjour aux États-Unis?", "ar": "ما هو الغرض الرئيسي من زيارتك أو إقامتك في الولايات المتحدة؟", "ru": "Какова основная цель вашего визита или пребывания в США?", "pt": "Qual é o objetivo principal da sua visita ou estadia nos Estados Unidos?", "hi": "संयुक्त राज्य अमेरिका में आपके दौरे या प्रवास का मुख्य उद्देश्य क्या है?", "ko": "미국 방문 또는 체류의 주요 목적은 무엇입니까?", "vi": "Mục đích chính của chuyến thăm hoặc lưu trú của bạn tại Hoa Kỳ là gì?"}'::jsonb, 1, 'single_choice'),
  ('{"en": "Which best describes your current situation?", "es": "¿Cuál describe mejor su situación actual?", "zh": "哪项最能描述您目前的情况？", "fr": "Laquelle décrit le mieux votre situation actuelle?", "ar": "أي مما يلي يصف وضعك الحالي بشكل أفضل؟", "ru": "Что лучше всего описывает вашу текущую ситуацию?", "pt": "Qual descreve melhor sua situação atual?", "hi": "आपकी वर्तमान स्थिति का सबसे अच्छा वर्णन कौन सा करता है?", "ko": "현재 상황을 가장 잘 설명하는 것은 무엇입니까?", "vi": "Điều nào mô tả tốt nhất tình huống hiện tại của bạn?"}'::jsonb, 2, 'single_choice'),
  ('{"en": "How long do you plan to stay in the United States?", "es": "¿Cuánto tiempo planea quedarse en Estados Unidos?", "zh": "您计划在美国停留多久？", "fr": "Combien de temps prévoyez-vous de rester aux États-Unis?", "ar": "كم من الوقت تخطط للبقاء في الولايات المتحدة؟", "ru": "Как долго вы планируете оставаться в США?", "pt": "Quanto tempo você planeja ficar nos Estados Unidos?", "hi": "आप संयुक्त राज्य अमेरिका में कितने समय तक रहने की योजना बना रहे हैं?", "ko": "미국에 얼마나 오래 머물 계획입니까?", "vi": "Bạn dự định ở lại Hoa Kỳ bao lâu?"}'::jsonb, 3, 'single_choice'),
  ('{"en": "Which country issued your current travel document or passport?", "es": "¿Qué país emitió su documento de viaje o pasaporte actual?", "zh": "哪个国家签发了您目前的旅行证件或护照？", "fr": "Quel pays a émis votre document de voyage ou passeport actuel?", "ar": "ما هي الدولة التي أصدرت وثيقة سفرك أو جواز سفرك الحالي؟", "ru": "Какая страна выдала ваш текущий проездной документ или паспорт?", "pt": "Qual país emitiu seu documento de viagem ou passaporte atual?", "hi": "आपका वर्तमान यात्रा दस्तावेज़ या पासपोर्ट किस देश ने जारी किया?", "ko": "현재 여행 서류 또는 여권을 발급한 국가는 어디입니까?", "vi": "Quốc gia nào đã cấp giấy tờ du lịch hoặc hộ chiếu hiện tại của bạn?"}'::jsonb, 4, 'single_choice');

-- Get question IDs
DO $$
DECLARE
  q1_id uuid;
  q2_id uuid;
  q3_id uuid;
  q4_id uuid;
BEGIN
  SELECT id INTO q1_id FROM quiz_questions WHERE question_order = 1;
  SELECT id INTO q2_id FROM quiz_questions WHERE question_order = 2;
  SELECT id INTO q3_id FROM quiz_questions WHERE question_order = 3;
  SELECT id INTO q4_id FROM quiz_questions WHERE question_order = 4;

  -- Options for Question 1 (Primary Purpose)
  INSERT INTO quiz_options (question_id, option_translations, option_order, visa_type_mapping)
  VALUES
    (q1_id, '{"en": "Tourism or vacation", "es": "Turismo o vacaciones", "zh": "旅游或度假", "fr": "Tourisme ou vacances", "ar": "السياحة أو الإجازة", "ru": "Туризм или отдых", "pt": "Turismo ou férias", "hi": "पर्यटन या छुट्टी", "ko": "관광 또는 휴가", "vi": "Du lịch hoặc nghỉ dưỡng"}'::jsonb, 1, ARRAY['b1b2', 'esta']),
    (q1_id, '{"en": "Business meetings or conferences", "es": "Reuniones de negocios o conferencias", "zh": "商务会议或会议", "fr": "Réunions d affaires ou conférences", "ar": "اجتماعات عمل أو مؤتمرات", "ru": "Деловые встречи или конференции", "pt": "Reuniões de negócios ou conferências", "hi": "व्यापार बैठकें या सम्मेलन", "ko": "비즈니스 회의 또는 컨퍼런스", "vi": "Các cuộc họp kinh doanh hoặc hội nghị"}'::jsonb, 2, ARRAY['b1b2', 'esta']),
    (q1_id, '{"en": "Academic study at a school or university", "es": "Estudio académico en una escuela o universidad", "zh": "在学校或大学进行学术学习", "fr": "Études académiques dans une école ou université", "ar": "الدراسة الأكاديمية في مدرسة أو جامعة", "ru": "Академическое обучение в школе или университете", "pt": "Estudo acadêmico em uma escola ou universidade", "hi": "स्कूल या विश्वविद्यालय में शैक्षणिक अध्ययन", "ko": "학교 또는 대학에서 학업", "vi": "Học tập học thuật tại trường hoặc đại học"}'::jsonb, 3, ARRAY['f1']),
    (q1_id, '{"en": "Vocational or technical training", "es": "Formación vocacional o técnica", "zh": "职业或技术培训", "fr": "Formation professionnelle ou technique", "ar": "التدريب المهني أو التقني", "ru": "Профессиональное или техническое обучение", "pt": "Treinamento vocacional ou técnico", "hi": "व्यावसायिक या तकनीकी प्रशिक्षण", "ko": "직업 또는 기술 훈련", "vi": "Đào tạo nghề hoặc kỹ thuật"}'::jsonb, 4, ARRAY['m1']),
    (q1_id, '{"en": "Employment or work", "es": "Empleo o trabajo", "zh": "就业或工作", "fr": "Emploi ou travail", "ar": "التوظيف أو العمل", "ru": "Трудоустройство или работа", "pt": "Emprego ou trabalho", "hi": "रोजगार या कार्य", "ko": "고용 또는 근무", "vi": "Việc làm hoặc công việc"}'::jsonb, 5, ARRAY['h1b', 'h2a', 'h2b', 'l1', 'o1', 'p1']),
    (q1_id, '{"en": "Cultural exchange or training program", "es": "Programa de intercambio cultural o capacitación", "zh": "文化交流或培训项目", "fr": "Programme d échange culturel ou de formation", "ar": "برنامج تبادل ثقافي أو تدريب", "ru": "Программа культурного обмена или обучения", "pt": "Programa de intercâmbio cultural ou treinamento", "hi": "सांस्कृतिक विनिमय या प्रशिक्षण कार्यक्रम", "ko": "문화 교류 또는 연수 프로그램", "vi": "Chương trình trao đổi văn hóa hoặc đào tạo"}'::jsonb, 6, ARRAY['j1']),
    (q1_id, '{"en": "Religious work or mission", "es": "Trabajo religioso o misión", "zh": "宗教工作或使命", "fr": "Travail religieux ou mission", "ar": "عمل ديني أو مهمة", "ru": "Религиозная работа или миссия", "pt": "Trabalho religioso ou missão", "hi": "धार्मिक कार्य या मिशन", "ko": "종교 활동 또는 선교", "vi": "Công việc tôn giáo hoặc sứ mệnh"}'::jsonb, 7, ARRAY['r1']),
    (q1_id, '{"en": "Media/journalism work", "es": "Trabajo de medios/periodismo", "zh": "媒体/新闻工作", "fr": "Travail médiatique/journalisme", "ar": "عمل إعلامي/صحافة", "ru": "Работа в СМИ/журналистика", "pt": "Trabalho de mídia/jornalismo", "hi": "मीडिया/पत्रकारिता का कार्य", "ko": "언론/저널리즘 업무", "vi": "Công việc truyền thông/báo chí"}'::jsonb, 8, ARRAY['i']),
    (q1_id, '{"en": "To marry or join my spouse", "es": "Para casarme o unirme a mi cónyuge", "zh": "结婚或与配偶团聚", "fr": "Pour me marier ou rejoindre mon conjoint", "ar": "للزواج أو الانضمام إلى زوجي/زوجتي", "ru": "Для вступления в брак или воссоединения с супругом", "pt": "Para casar ou me juntar ao meu cônjuge", "hi": "शादी करने या अपने जीवनसाथी से जुड़ने के लिए", "ko": "결혼하거나 배우자와 합류하기 위해", "vi": "Để kết hôn hoặc hợp với vợ/chồng"}'::jsonb, 9, ARRAY['k1', 'k3']),
    (q1_id, '{"en": "Permanent residence", "es": "Residencia permanente", "zh": "永久居留", "fr": "Résidence permanente", "ar": "الإقامة الدائمة", "ru": "Постоянное проживание", "pt": "Residência permanente", "hi": "स्थायी निवास", "ko": "영주", "vi": "Cư trú vĩnh viễn"}'::jsonb, 10, ARRAY['greencard']);

  -- Options for Question 2 (Current Situation)
  INSERT INTO quiz_options (question_id, option_translations, option_order, visa_type_mapping)
  VALUES
    (q2_id, '{"en": "I have a job offer in a specialized field", "es": "Tengo una oferta de trabajo en un campo especializado", "zh": "我在专业领域有工作机会", "fr": "J ai une offre d emploi dans un domaine spécialisé", "ar": "لدي عرض عمل في مجال متخصص", "ru": "У меня есть предложение о работе в специализированной области", "pt": "Tenho uma oferta de emprego em um campo especializado", "hi": "मेरे पास एक विशेष क्षेत्र में नौकरी का प्रस्ताव है", "ko": "전문 분야에서 일자리 제안이 있습니다", "vi": "Tôi có lời mời làm việc trong lĩnh vực chuyên môn"}'::jsonb, 1, ARRAY['h1b']),
    (q2_id, '{"en": "I work for agriculture or seasonal work", "es": "Trabajo en agricultura o trabajo estacional", "zh": "我从事农业或季节性工作", "fr": "Je travaille dans l agriculture ou le travail saisonnier", "ar": "أعمل في الزراعة أو العمل الموسمي", "ru": "Я работаю в сельском хозяйстве или на сезонной работе", "pt": "Trabalho na agricultura ou trabalho sazonal", "hi": "मैं कृषि या मौसमी काम के लिए काम करता हूं", "ko": "농업 또는 계절 작업을 합니다", "vi": "Tôi làm việc nông nghiệp hoặc công việc theo mùa"}'::jsonb, 2, ARRAY['h2a', 'h2b']),
    (q2_id, '{"en": "I am being transferred by my company", "es": "Mi empresa me está transfiriendo", "zh": "我正在被公司调动", "fr": "Je suis transféré par mon entreprise", "ar": "يتم نقلي من قبل شركتي", "ru": "Меня переводит моя компания", "pt": "Estou sendo transferido pela minha empresa", "hi": "मुझे मेरी कंपनी द्वारा स्थानांतरित किया जा रहा है", "ko": "회사에서 저를 전근시키고 있습니다", "vi": "Tôi đang được công ty chuyển giao"}'::jsonb, 3, ARRAY['l1']),
    (q2_id, '{"en": "I have extraordinary abilities in my field", "es": "Tengo habilidades extraordinarias en mi campo", "zh": "我在我的领域有非凡的能力", "fr": "J ai des capacités extraordinaires dans mon domaine", "ar": "لدي قدرات استثنائية في مجالي", "ru": "У меня выдающиеся способности в моей области", "pt": "Tenho habilidades extraordinárias em meu campo", "hi": "मेरे क्षेत्र में मेरे पास असाधारण क्षमताएं हैं", "ko": "제 분야에서 특별한 능력이 있습니다", "vi": "Tôi có năng lực phi thường trong lĩnh vực của mình"}'::jsonb, 4, ARRAY['o1']),
    (q2_id, '{"en": "I am a professional athlete or entertainer", "es": "Soy atleta profesional o artista", "zh": "我是职业运动员或演艺人员", "fr": "Je suis athlète professionnel ou artiste", "ar": "أنا رياضي محترف أو فنان", "ru": "Я профессиональный спортсмен или артист", "pt": "Sou atleta profissional ou artista", "hi": "मैं एक पेशेवर एथलीट या कलाकार हूं", "ko": "저는 프로 운동선수 또는 연예인입니다", "vi": "Tôi là vận động viên chuyên nghiệp hoặc nghệ sĩ"}'::jsonb, 5, ARRAY['p1']),
    (q2_id, '{"en": "I am enrolled in an academic program", "es": "Estoy inscrito en un programa académico", "zh": "我已注册学术课程", "fr": "Je suis inscrit dans un programme académique", "ar": "أنا مسجل في برنامج أكاديمي", "ru": "Я зачислен в академическую программу", "pt": "Estou matriculado em um programa acadêmico", "hi": "मैं एक शैक्षणिक कार्यक्रम में नामांकित हूं", "ko": "학업 프로그램에 등록했습니다", "vi": "Tôi đang theo học chương trình học thuật"}'::jsonb, 6, ARRAY['f1']),
    (q2_id, '{"en": "I am in a vocational training program", "es": "Estoy en un programa de formación vocacional", "zh": "我在职业培训课程中", "fr": "Je suis dans un programme de formation professionnelle", "ar": "أنا في برنامج تدريب مهني", "ru": "Я прохожу профессиональное обучение", "pt": "Estou em um programa de treinamento vocacional", "hi": "मैं एक व्यावसायिक प्रशिक्षण कार्यक्रम में हूं", "ko": "직업 훈련 프로그램에 있습니다", "vi": "Tôi đang trong chương trình đào tạo nghề"}'::jsonb, 7, ARRAY['m1']),
    (q2_id, '{"en": "I am in an exchange program", "es": "Estoy en un programa de intercambio", "zh": "我在交流项目中", "fr": "Je suis dans un programme d échange", "ar": "أنا في برنامج تبادل", "ru": "Я участвую в программе обмена", "pt": "Estou em um programa de intercâmbio", "hi": "मैं एक विनिमय कार्यक्रम में हूं", "ko": "교환 프로그램에 있습니다", "vi": "Tôi đang trong chương trình trao đổi"}'::jsonb, 8, ARRAY['j1']),
    (q2_id, '{"en": "I am engaged to a U.S. citizen", "es": "Estoy comprometido con un ciudadano estadounidense", "zh": "我与美国公民订婚", "fr": "Je suis fiancé à un citoyen américain", "ar": "أنا مخطوب لمواطن أمريكي", "ru": "Я помолвлен с гражданином США", "pt": "Estou noivo de um cidadão americano", "hi": "मैं एक अमेरिकी नागरिक से सगाई कर चुका हूं", "ko": "미국 시민권자와 약혼했습니다", "vi": "Tôi đã đính hôn với công dân Mỹ"}'::jsonb, 9, ARRAY['k1']),
    (q2_id, '{"en": "I am married to a U.S. citizen", "es": "Estoy casado con un ciudadano estadounidense", "zh": "我与美国公民结婚", "fr": "Je suis marié à un citoyen américain", "ar": "أنا متزوج من مواطن أمريكي", "ru": "Я женат/замужем за гражданином США", "pt": "Sou casado com um cidadão americano", "hi": "मैं एक अमेरिकी नागरिक से शादीशुदा हूं", "ko": "미국 시민권자와 결혼했습니다", "vi": "Tôi đã kết hôn với công dân Mỹ"}'::jsonb, 10, ARRAY['k3', 'greencard']),
    (q2_id, '{"en": "I am a religious worker", "es": "Soy un trabajador religioso", "zh": "我是宗教工作者", "fr": "Je suis un travailleur religieux", "ar": "أنا عامل ديني", "ru": "Я религиозный работник", "pt": "Sou um trabalhador religioso", "hi": "मैं एक धार्मिक कार्यकर्ता हूं", "ko": "저는 종교 활동가입니다", "vi": "Tôi là nhân viên tôn giáo"}'::jsonb, 11, ARRAY['r1']),
    (q2_id, '{"en": "I am a journalist or media representative", "es": "Soy periodista o representante de medios", "zh": "我是记者或媒体代表", "fr": "Je suis journaliste ou représentant des médias", "ar": "أنا صحفي أو ممثل إعلامي", "ru": "Я журналист или представитель СМИ", "pt": "Sou jornalista ou representante de mídia", "hi": "मैं एक पत्रकार या मीडिया प्रतिनिधि हूं", "ko": "저는 기자 또는 언론 대표입니다", "vi": "Tôi là nhà báo hoặc đại diện truyền thông"}'::jsonb, 12, ARRAY['i']),
    (q2_id, '{"en": "I am just visiting for tourism", "es": "Solo estoy visitando por turismo", "zh": "我只是来旅游", "fr": "Je visite juste pour le tourisme", "ar": "أنا فقط أزور للسياحة", "ru": "Я просто приехал на отдых", "pt": "Estou apenas visitando por turismo", "hi": "मैं केवल पर्यटन के लिए जा रहा हूं", "ko": "관광 목적으로만 방문합니다", "vi": "Tôi chỉ đến thăm du lịch"}'::jsonb, 13, ARRAY['b1b2', 'esta']),
    (q2_id, '{"en": "I have family sponsoring me for permanent residence", "es": "Tengo familia que me patrocina para residencia permanente", "zh": "我有家人为我担保永久居留", "fr": "J ai de la famille qui me parraine pour la résidence permanente", "ar": "لدي عائلة ترعاني للإقامة الدائمة", "ru": "У меня есть семья, спонсирующая меня для постоянного проживания", "pt": "Tenho família me patrocinando para residência permanente", "hi": "मेरे पास परिवार है जो मुझे स्थायी निवास के लिए प्रायोजित कर रहा है", "ko": "영주권을 위해 가족이 저를 후원하고 있습니다", "vi": "Tôi có gia đình bảo lãnh cho cư trú vĩnh viễn"}'::jsonb, 14, ARRAY['greencard']);

  -- Options for Question 3 (Duration)
  INSERT INTO quiz_options (question_id, option_translations, option_order, visa_type_mapping)
  VALUES
    (q3_id, '{"en": "90 days or less", "es": "90 días o menos", "zh": "90天或更短", "fr": "90 jours ou moins", "ar": "90 يومًا أو أقل", "ru": "90 дней или менее", "pt": "90 dias ou menos", "hi": "90 दिन या उससे कम", "ko": "90일 이하", "vi": "90 ngày trở xuống"}'::jsonb, 1, ARRAY['b1b2', 'esta']),
    (q3_id, '{"en": "Several months (temporary work/training)", "es": "Varios meses (trabajo/capacitación temporal)", "zh": "几个月（临时工作/培训）", "fr": "Plusieurs mois (travail/formation temporaire)", "ar": "عدة أشهر (عمل/تدريب مؤقت)", "ru": "Несколько месяцев (временная работа/обучение)", "pt": "Vários meses (trabalho/treinamento temporário)", "hi": "कई महीने (अस्थायी काम/प्रशिक्षण)", "ko": "몇 달 (임시 근무/훈련)", "vi": "Vài tháng (công việc/đào tạo tạm thời)"}'::jsonb, 2, ARRAY['h2a', 'h2b', 'j1']),
    (q3_id, '{"en": "1-3 years (study program)", "es": "1-3 años (programa de estudio)", "zh": "1-3年（学习项目）", "fr": "1-3 ans (programme d études)", "ar": "1-3 سنوات (برنامج دراسي)", "ru": "1-3 года (учебная программа)", "pt": "1-3 anos (programa de estudo)", "hi": "1-3 वर्ष (अध्ययन कार्यक्रम)", "ko": "1-3년 (학업 프로그램)", "vi": "1-3 năm (chương trình học tập)"}'::jsonb, 3, ARRAY['f1', 'm1']),
    (q3_id, '{"en": "3+ years (long-term employment)", "es": "3+ años (empleo a largo plazo)", "zh": "3年以上（长期就业）", "fr": "3+ ans (emploi à long terme)", "ar": "3+ سنوات (توظيف طويل الأجل)", "ru": "3+ года (долгосрочная работа)", "pt": "3+ anos (emprego de longo prazo)", "hi": "3+ वर्ष (दीर्घकालिक रोजगार)", "ko": "3년 이상 (장기 고용)", "vi": "3+ năm (việc làm dài hạn)"}'::jsonb, 4, ARRAY['h1b', 'l1', 'o1', 'p1', 'r1', 'i']),
    (q3_id, '{"en": "Indefinitely (permanent residence)", "es": "Indefinidamente (residencia permanente)", "zh": "无限期（永久居留）", "fr": "Indéfiniment (résidence permanente)", "ar": "إلى أجل غير مسمى (إقامة دائمة)", "ru": "Неопределенное время (постоянное проживание)", "pt": "Indefinidamente (residência permanente)", "hi": "अनिश्चित काल (स्थायी निवास)", "ko": "무기한 (영주)", "vi": "Vô thời hạn (cư trú vĩnh viễn)"}'::jsonb, 5, ARRAY['greencard', 'k3']);

  -- Options for Question 4 (Country/VWP)
  INSERT INTO quiz_options (question_id, option_translations, option_order, visa_type_mapping)
  VALUES
    (q4_id, '{"en": "A Visa Waiver Program country", "es": "Un país del Programa de Exención de Visa", "zh": "免签证计划国家", "fr": "Un pays du Programme d Exemption de Visa", "ar": "دولة من برنامج الإعفاء من التأشيرة", "ru": "Страна Программы безвизового въезда", "pt": "Um país do Programa de Isenção de Visto", "hi": "वीज़ा छूट कार्यक्रम देश", "ko": "비자 면제 프로그램 국가", "vi": "Quốc gia thuộc Chương trình Miễn Thị thực"}'::jsonb, 1, ARRAY['esta']),
    (q4_id, '{"en": "United States", "es": "Estados Unidos", "zh": "美国", "fr": "États-Unis", "ar": "الولايات المتحدة", "ru": "США", "pt": "Estados Unidos", "hi": "संयुक्त राज्य अमेरिका", "ko": "미국", "vi": "Hoa Kỳ"}'::jsonb, 2, ARRAY['greencard']),
    (q4_id, '{"en": "Another country", "es": "Otro país", "zh": "其他国家", "fr": "Un autre pays", "ar": "دولة أخرى", "ru": "Другая страна", "pt": "Outro país", "hi": "अन्य देश", "ko": "다른 나라", "vi": "Quốc gia khác"}'::jsonb, 3, ARRAY['b1b2', 'f1', 'm1', 'h1b', 'h2a', 'h2b', 'l1', 'o1', 'p1', 'j1', 'k1', 'k3', 'r1', 'i']);
END $$;